influxdb:
  image: tutum/influxdb:latest
  hostname: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "2003:2003"
  volumes:
    - ./env/influxdb/config.toml:/config/config.toml
  environment:
    - PRE_CREATE_DB=gatling;grafana

gatling:
  image: webdizz/gatling
  volumes:
    - ./perf-tst/src/test/scala:/opt/gatling/user-files/simulations
    - ./perf-tst/src/test/resources:/opt/gatling/user-files/data
    - ./results:/opt/results
    - ./env/gatling/gatling.conf:/opt/gatling/conf/gatling.conf
  command: /opt/gatling/bin/gatling.sh -m -s SearchForPatient -rf /opt/results

grafana:
  image: tutum/grafana
  ports:
    - "80:80"
  links:
    - influxdb
  volumes:
    - ./env/grafana/default.json:/app/app/dashboards/default.json
    - ./env/grafana/config.js:/app/config.js
    - ./env/grafana/.influx_db_configured:/.influx_db_configured
  environment:
    - INFLUXDB_IS_GRAFANADB=true
    - INFLUXDB_HOST=192.168.176.128
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=gatling
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root
    - HTTP_PASS=grafana

service:
  image: webdizz/baseimage-java8:8u60
  command: java -jar /patient-service-all.jar
  ports:
    - "8080:8080"
  volumes:
    - ./patient-service/build/libs/patient-service-all.jar:/patient-service-all.jar