influxdb:
  image: tutum/influxdb:latest
  hostname: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "2003:2003"
  volumes:
    - ./env/influxdb/config.toml:/config/config.toml
  environment:
    - PRE_CREATE_DB=gatling;grafana

gatling:
  image: webdizz/gatling
  volumes:
    - ./perf-tst/src/test/scala:/opt/gatling/user-files/simulations
    - ./perf-tst/src/test/resources:/opt/gatling/user-files/data
    - ./results:/opt/results
    - ./env/gatling/gatling.conf:/opt/gatling/conf/gatling.conf
  command: /opt/gatling/bin/gatling.sh -m -s PatientServiceLoadScenario -rf /opt/results

grafana:
  image: fabric8/grafana
  ports:
    - "80:3000"
  links:
    - influxdb
  volumes:
    - ./env/grafana/perfdash.js:/usr/share/grafana/public/dashboards/perfdash.js
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=grafana

service:
  image: webdizz/baseimage-java8:8u60
  command: java -jar /patient-service-all.jar
  ports:
    - "8080:8080"
  volumes:
    - ./patient-service/build/libs/patient-service-all.jar:/patient-service-all.jar